Repository zenuix/Zen-UI, pull requests merged in 2025-03, with the labels that each got.

#6 Feature/#3 modal
  package.json
  pnpm-lock.yaml
  src/components/modal/Modal.tsx
  src/components/modal/context.tsx
  src/components/modal/hook.ts
  src/components/modal/index.ts
  src/components/modal/style.css
  src/components/modal/subcomponents/Container.tsx
  src/components/modal/subcomponents/Content.tsx
  src/components/modal/subcomponents/Description.tsx
  src/components/modal/subcomponents/Footer.tsx
  src/components/modal/subcomponents/Header.tsx
  src/components/modal/subcomponents/Title.tsx
  src/components/modal/subcomponents/Trigger.tsx
  src/components/modal/type.ts
  src/components/modal/util.ts
  src/global-style.css
Labels: Feature, Setting

#16 Feature/#10 dropdown menu
  src/components/dropdown/context.tsx
  src/components/dropdown/dropdown.tsx
  src/components/dropdown/index.ts
  src/components/dropdown/subcomponents/dropdown-content.tsx
  src/components/dropdown/subcomponents/dropdown-group.tsx
  src/components/dropdown/subcomponents/dropdown-item.tsx
  src/components/dropdown/subcomponents/dropdown-separator.tsx
  src/components/dropdown/subcomponents/dropdown-trigger.tsx
  src/components/dropdown/type.ts
Labels: Feature

#19 Feature/#13 tabs
  src/components/tabs/context.tsx
  src/components/tabs/index.ts
  src/components/tabs/style.css
  src/components/tabs/subcomponents/content-group.tsx
  src/components/tabs/subcomponents/content.tsx
  src/components/tabs/subcomponents/tab-group.tsx
  src/components/tabs/subcomponents/tab.tsx
  src/components/tabs/tabs.tsx
  src/components/tabs/type.ts
  src/components/tabs/utils.ts
Labels: Feature

#24 style : 글로벌 스타일 추가
  src/global-style.css
Labels: Styles

#18 Feature/#3 modal
  src/components/modal/Modal.tsx
  src/components/modal/context.tsx
  src/components/modal/hook.ts
  src/components/modal/index.ts
  src/components/modal/style.css
  src/components/modal/subcomponents/Container.tsx
  src/components/modal/subcomponents/Content.tsx
  src/components/modal/subcomponents/Description.tsx
  src/components/modal/subcomponents/Footer.tsx
  src/components/modal/subcomponents/Header.tsx
  src/components/modal/subcomponents/Title.tsx
  src/components/modal/subcomponents/Trigger.tsx
  src/components/modal/subcomponents/modal-close-button.tsx
  src/components/modal/subcomponents/modal-container.tsx
  src/components/modal/subcomponents/modal-content.tsx
  src/components/modal/subcomponents/modal-description.tsx
  src/components/modal/subcomponents/modal-footer.tsx
  src/components/modal/subcomponents/modal-header.tsx
  src/components/modal/subcomponents/modal-overlay.tsx
  src/components/modal/subcomponents/modal-title.tsx
  src/components/modal/subcomponents/modal-trigger.tsx
  src/components/modal/type.ts
  src/global-hooks.ts
Labels: Feature, Styles

#21 Feature/#5 breadcrumbs
  package.json
  pnpm-lock.yaml
  src/components/breadcrumb/breadcrumb.stories.tsx
  src/components/breadcrumb/breadcrumb.tsx
  src/components/breadcrumb/hook.tsx
  src/components/breadcrumb/index.ts
  src/components/breadcrumb/style.css
  src/components/breadcrumb/subcomponents/breadcrumb-ellipsis.tsx
  src/components/breadcrumb/subcomponents/breadcrumb-item.tsx
  src/components/breadcrumb/subcomponents/breadcrumb-link.tsx
  src/components/breadcrumb/subcomponents/breadcrumb-list.tsx
  src/components/breadcrumb/subcomponents/breadcrumb-page.tsx
  src/components/breadcrumb/subcomponents/breadcrumb-separator.tsx
  src/components/breadcrumb/type.ts
  src/components/breadcrumb/util.ts
Labels: Feature

#27 Bug fix/#25 breadcrumb custom hook fix
  src/components/breadcrumb/breadcrumb.stories.tsx
  src/components/breadcrumb/hook.tsx
  src/components/breadcrumb/subcomponents/breadcrumb-list.tsx
  src/components/breadcrumb/type.ts
Labels: BugFix

#26 Feature/#3 modal
  src/components/modal/modal.stories.tsx
  src/components/modal/style.css
  src/components/modal/subcomponents/modal-close-button.tsx
  src/components/modal/subcomponents/modal-container.tsx
  src/components/modal/subcomponents/modal-content.tsx
  src/components/modal/subcomponents/modal-description.tsx
  src/components/modal/subcomponents/modal-footer.tsx
  src/components/modal/subcomponents/modal-header.tsx
  src/components/modal/subcomponents/modal-overlay.tsx
  src/components/modal/subcomponents/modal-title.tsx
  src/components/modal/subcomponents/modal-trigger.tsx
  src/components/modal/type.ts
  src/global-style.css
Labels: Styles, Refactor

#33 [Release]
  package.json
  pnpm-lock.yaml
  src/components/breadcrumb/breadcrumb.stories.tsx
  src/components/breadcrumb/breadcrumb.tsx
  src/components/breadcrumb/hook.tsx
  src/components/breadcrumb/index.ts
  src/components/breadcrumb/style.css
  src/components/breadcrumb/subcomponents/breadcrumb-ellipsis.tsx
  src/components/breadcrumb/subcomponents/breadcrumb-item.tsx
  src/components/breadcrumb/subcomponents/breadcrumb-link.tsx
  src/components/breadcrumb/subcomponents/breadcrumb-list.tsx
  src/components/breadcrumb/subcomponents/breadcrumb-page.tsx
  src/components/breadcrumb/subcomponents/breadcrumb-separator.tsx
  src/components/breadcrumb/type.ts
  src/components/breadcrumb/util.ts
  src/components/dropdown/context.tsx
  src/components/dropdown/dropdown.tsx
  src/components/dropdown/hook.ts
  src/components/dropdown/index.ts
  src/components/dropdown/style.css
  src/components/dropdown/subcomponents/dropdown-content.tsx
  src/components/dropdown/subcomponents/dropdown-group.tsx
  src/components/dropdown/subcomponents/dropdown-item.tsx
  src/components/dropdown/subcomponents/dropdown-separator.tsx
  src/components/dropdown/subcomponents/dropdown-trigger.tsx
  src/components/dropdown/type.ts
  src/components/modal/Modal.tsx
  src/components/modal/context.tsx
  src/components/modal/hook.ts
  src/components/modal/index.ts
  src/components/modal/modal.stories.tsx
  src/components/modal/style.css
  src/components/modal/subcomponents/modal-close-button.tsx
  src/components/modal/subcomponents/modal-container.tsx
  src/components/modal/subcomponents/modal-content.tsx
  src/components/modal/subcomponents/modal-description.tsx
  src/components/modal/subcomponents/modal-footer.tsx
  src/components/modal/subcomponents/modal-header.tsx
  src/components/modal/subcomponents/modal-overlay.tsx
  src/components/modal/subcomponents/modal-title.tsx
  src/components/modal/subcomponents/modal-trigger.tsx
  src/components/modal/type.ts
  src/components/modal/util.ts
  src/components/tabs/context.tsx
  src/components/tabs/index.ts
  src/components/tabs/style.css
  src/components/tabs/subcomponents/content-group.tsx
  src/components/tabs/subcomponents/content.tsx
  src/components/tabs/subcomponents/tab-group.tsx
  src/components/tabs/subcomponents/tab.tsx
  src/components/tabs/tabs.tsx
  src/components/tabs/type.ts
  src/components/tabs/utils.ts
  src/global-hooks.ts
  src/global-style.css
  src/main.tsx
Labels: Deploy

#34 fix:#3 파일명 대소문자 변경
  src/components/modal/modal.tsx
Labels: BugFix

#28 Feature/#10 dropdown close
  src/components/dropdown/context.tsx
  src/components/dropdown/dropdown.stories.tsx
  src/components/dropdown/style.css
  src/components/dropdown/subcomponents/dropdown-content.tsx
  src/components/dropdown/subcomponents/dropdown-item.tsx
  src/components/dropdown/subcomponents/dropdown-trigger.tsx
  src/components/dropdown/type.ts
  src/global-hooks.ts
Labels: Feature

#37 Feature/#36 breadcrumblist constraint
  src/components/breadcrumb/breadcrumb.stories.tsx
  src/components/breadcrumb/breadcrumb.tsx
  src/components/breadcrumb/style.css
  src/components/breadcrumb/subcomponents/breadcrumb-list.tsx
  src/components/breadcrumb/util.ts
Labels: Feature, Styles

#41 Feature/#13 tabs
  src/components/tabs/Tabs.stories.tsx
  src/components/tabs/context.tsx
  src/components/tabs/hook.tsx
  src/components/tabs/style.css
  src/components/tabs/subcomponents/content-group.tsx
  src/components/tabs/subcomponents/content.tsx
  src/components/tabs/subcomponents/tab-group.tsx
  src/components/tabs/subcomponents/tab.tsx
  src/components/tabs/tabs.tsx
  src/components/tabs/type.ts
  src/components/tabs/utils.ts
Labels: Feature
